services:
  postgres:
    image: postgres:13.10
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U async_postgres -d async_work_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  sqlalchemy:
    build: ./work_2
    container_name: sqlalchemy
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    restart: on-failure